feat(sensing-messages): add sensing messages
autowarefoundation/autoware_msgs pull request #24
Opened 2022-06-09 15:43 UTC by xmfcx

## Description

This PR adds the sensing messages.

Related discussions/issues:
- https://github.com/orgs/autowarefoundation/discussions/216

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2022-06-09 21:39 UTC, xmfcx commented
I've finalized this PR for the GNSS/INS related messages. I've put the localization design information to the readme file too but we can separate it later.

Some points:
- I didn't want to use the [sensor_msgs/IMU](https://docs.ros.org/en/api/sensor_msgs/html/msg/Imu.html) message because it lacks the linear velocity and angular acceleration fields.
- I didn't want to use [sensor_msgs/NavSatFix](https://docs.ros.org/en/api/sensor_msgs/html/msg/NavSatFix.html) because it has fields not used by the Autoware:
  - [sensor_msgs/NavSatStatus](https://docs.ros.org/en/api/sensor_msgs/html/msg/NavSatStatus.html) status
  - `uint8` position_covariance_type
  - `float64[9]` position_covariance (we are only using the diagonal)

Please review this and share your opinions.

2022-06-10 03:37 UTC, kenji-miyake commented on autoware_sensing_msgs/README.md
> +| <span> | <span> | <span> | <span> | <span> | <span> |
[style] Adding an empty line here enables auto-formatting of the table.

```suggestion

| <span> | <span> | <span> | <span> | <span> | <span> |
```

2022-06-10 03:50 UTC, kenji-miyake reviewed
At a glance, generally looks good. :+1: Thank you for adding these msgs!
The members of TIER IV's localization team will review the details.

2022-06-10 09:24 UTC, angry-crab commented
LGTM.
The only concern is that [sensor_msgs/NavSatStatus](https://docs.ros.org/en/api/sensor_msgs/html/msg/NavSatStatus.html) might be needed if we want to drop some non-fixed messages.

2022-06-10 13:27 UTC, xmfcx commented
> LGTM. My only concern is that [sensor_msgs/NavSatStatus](https://docs.ros.org/en/api/sensor_msgs/html/msg/NavSatStatus.html) might be needed if we want to drop some non-fixed messages.

It is the job of the driver/bridge to attach these values to the readings. If a message is non-fixed, they should not publish the message or assign very high RMSE values, depending on the confidence level.

2022-06-27 15:30 UTC, meliketanrikulu requested changes

2022-06-27 15:30 UTC, meliketanrikulu commented on autoware_sensing_msgs/README.md
> +For this information, you can use the [AccelWithCovariance](https://docs.ros.org/en/api/geometry_msgs/html/msg/AccelWithCovariance.html) message.
```suggestion
For this information, you can use the [AccelWithCovarianceStamped](https://docs.ros.org/en/api/geometry_msgs/html/msg/AccelWithCovarianceStamped.html) message.
```

2022-07-04 16:48 UTC, meliketanrikulu approved these changes

2022-07-04 16:49 UTC, meliketanrikulu approved these changes

2022-07-04 16:59 UTC, xmfcx commented
@angry-crab I've replaced the GnssInsPosition message with the NavSatFix for compatibility. Could you review it again?

Also if @YamatoAndo @mitsudome-r @yukkysaito could review it'd be nice, some other tasks are blocked by this.

2022-07-05 01:00 UTC, yukkysaito approved these changes
sorry for late :pray: 
LGTM

2022-07-05 01:00 UTC, merged